const SysApis = {
    //系统接口 system
    login: '/api/system/login',
    logout: '/api/system/logout',
    userInfo: '/api/system/userInfo',
    menus: '/api/system/menus/user',
    permissions: '/api/system/permissions',
    checkUsername: '/api/system/checkUsername',
    //用户 user
    addUser: '/api/system/user/add',
    editUser: '/api/system/user/edit',
    userRoleList: '/api/system/roles/user',
    resetPassword: '/api/system/user/password/reset',
    updatePassword: '/api/system/user/updatePassword',
    userListPage: '/api/system/user/page',
    delUser: '/api/system/user/del',
    lockUser: '/api/system/user/lock',
    unlockUser: '/api/system/user/unlock',
    //菜单 menus
    menusList: '/api/system/menus/list',
    delMenus: '/api/system/menus/remove',
    saveMenus: '/api/system/menus/save',
    roleMenus: '/api/system/menus/role',
    //角色 roles
    rolesList: '/api/system/roles/list',
    delRoles: '/api/system/roles/remove',
    saveRoles: '/api/system/roles/save',
}
export {SysApis}
